# Form implementation generated from reading ui file 'AutorizationWin.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AutorizationWindow(object):
    def setupUi(self, AutorizationWindow):
        AutorizationWindow.setObjectName("AutorizationWindow")
        AutorizationWindow.resize(800, 600)
        AutorizationWindow.setMinimumSize(QtCore.QSize(800, 600))
        AutorizationWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../xlsx/32.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AutorizationWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=AutorizationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(220, 150, 371, 211))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 351, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.autorizationbtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.autorizationbtn.setFont(font)
        self.autorizationbtn.setObjectName("autorizationbtn")
        self.gridLayout_2.addWidget(self.autorizationbtn, 2, 0, 1, 2)
        self.login = QtWidgets.QLabel(parent=self.layoutWidget)
        self.login.setObjectName("login")
        self.gridLayout_2.addWidget(self.login, 0, 0, 1, 1)
        self.login_input = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.login_input.setObjectName("login_input")
        self.gridLayout_2.addWidget(self.login_input, 0, 1, 1, 1)
        self.password = QtWidgets.QLabel(parent=self.layoutWidget)
        self.password.setObjectName("password")
        self.gridLayout_2.addWidget(self.password, 1, 0, 1, 1)
        self.password_input = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.password_input.setText("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_input.setObjectName("password_input")
        self.gridLayout_2.addWidget(self.password_input, 1, 1, 1, 1)
        self.badautorization = QtWidgets.QLabel(parent=self.groupBox)
        self.badautorization.setGeometry(QtCore.QRect(0, 190, 371, 21))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.badautorization.setFont(font)
        self.badautorization.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.badautorization.setAutoFillBackground(False)
        self.badautorization.setStyleSheet("color: rgb(255, 0, 4);")
        self.badautorization.setText("")
        self.badautorization.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.badautorization.setScaledContents(False)
        self.badautorization.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.badautorization.setWordWrap(False)
        self.badautorization.setObjectName("badautorization")
        AutorizationWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=AutorizationWindow)
        self.statusbar.setObjectName("statusbar")
        AutorizationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AutorizationWindow)
        QtCore.QMetaObject.connectSlotsByName(AutorizationWindow)

    def retranslateUi(self, AutorizationWindow):
        _translate = QtCore.QCoreApplication.translate
        AutorizationWindow.setWindowTitle(_translate("AutorizationWindow", "Авторизация"))
        self.groupBox.setTitle(_translate("AutorizationWindow", "АВТОРИЗАЦИЯ"))
        self.autorizationbtn.setText(_translate("AutorizationWindow", "ВОЙТИ"))
        self.login.setText(_translate("AutorizationWindow", "ЛОГИН"))
        self.password.setText(_translate("AutorizationWindow", "ПАРОЛЬ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AutorizationWindow = QtWidgets.QMainWindow()
    ui = Ui_AutorizationWindow()
    ui.setupUi(AutorizationWindow)
    AutorizationWindow.show()
    sys.exit(app.exec())
